### ISSUE TITLE
Hostable with Bridge Deployer?

### ISSUE THREAD

**Issue by kubo6472** [beeper/meetbot#10]
Will this be hostable with [Beeper/Bridge-Deployer](https://github.com/beeper/bridge-deployer/) at any time in the future, please?

**Comment by sumnerevans** [comment]
It's not a bridge, so probably not.

**Comment by kubo6472** [comment]
I meant it in a way as if this was runnable on fly.io with the same kind of site like https://self-host.beeper.com/
